baseURL = 'https://glossopkindervelo.co.uk'
languageCode = 'en'
title = 'Glossop Kinder Velo'
theme = 'ananke'

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Khem Sattaur"
favicon = "favicon.ico"
site_logo = "images/GKV_logo-whitebg.svg"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-30"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "bluesky",
  "x-twitter",
  "instagram",
  "strava",
  "flickr",
]

[params.ananke.social.facebook]
username = "GKVCC"
# profilelink = "https://www.facebook.com/GKVCC/"

[params.ananke.social.bluesky]
username = "gkvcc.bsky.social"

[params.ananke.social.bc]
# profilelink = "https://www.britishcycling.org.uk/club/profile/851/glossop-kinder-velo-cycling-club/"

[params.ananke.social.email]
email = "glossopkindervelo@gmail.com"

[params.ananke.social.x-twitter]
username = "gkvcc"

[params.ananke.social.whatsapp]
link = "https://chat.whatsapp.com/HX5Lq3BuL1sJo1R0SETfc1"

[params.ananke.social.instagram]
username = "glossopkv"

[params.ananke.social.strava]
username = "GKVCC"

[params.ananke.social.flickr]
username = "92639046@N07"